Thalia/views.py
from urllib.parse import urljoin

from flask import Blueprint, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user
from werkzeug.urls import url_parse

from .extensions import db
from .forms import FeedbackForm, LoginForm, RegistrationForm
from .models.portfolio import Portfolio
from .models.user import User

server_bp = Blueprint("main", __name__)


@server_bp.route("/", methods=["GET", "POST"])
def index():
    form = RegistrationForm()
    if form.validate_on_submit():
        if existing_username(form.username.data):
            error = "already registered"
            return render_template(
                "index.html", form=form, error=error, scroll="login_failed"
            )
        else:
            save_user(form.username.data, form.password.data)
            return redirect(url_for("main.login"))

    if form.is_submitted():
        return render_template("index.html", form=form, scroll="login_failed")

    return render_template("index.html", title="Home Page", form=form)


@server_bp.route("/about/")
def about():
    return render_template("about.html", title="About Page")


@server_bp.route("/us/")
def us():
    return render_template("us.html", title="About Us")


@server_bp.route("/contact/", methods=["GET", "POST"])
def contact():
    form = FeedbackForm()
    if form.validate_on_submit():
        # dump to feedback.csv
        with open("feedback.csv", "a") as file:
            file.write(
                "{},{},{}\n".format(
                    form.email.data, form.title.data, form.contents.data
                )
            )
    return render_template("contact.html", title="Contact Us", form=form)


@server_bp.route("/share/", methods=["POST"])
@login_required
def share_portfolio():
    portfolio_id = request.get_json().get("portfolio_id")
    portfolio = Portfolio.query.get(portfolio_id)
    if portfolio.owner != current_user.id:
        pass  # add redirect to 404
        return "404"
    else:
        uuid = portfolio.share()
        return uuid


@server_bp.route("/gallery/", methods=["GET"])
@login_required
def gallery():
    """
    We extract relevant values from the portfolio record into a separate array
    as we can not overwrite the strategy attribute of a Portfolio
    record with a strategy object, since it is not JSON serializable.
    An unelegant workaround, but it works.

    Also has post method for handling deletion and sharing
    """
    portfolios = []
    for p in Portfolio.query.filter_by(owner=current_user.id):
        portfolio = {"id": p.id, "name": p.name, "strat": p.get_strategy()}
        if p.uuid:
            portfolio["link"] = urljoin(
                request.host_url, url_for("/dashboard/") + p.uuid
            )
        else:
            portfolio["link"] = None
        portfolios.append(portfolio)

    return render_template("gallery.html", title="My Portfolios", portfolios=portfolios)


@server_bp.route("/login/", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        error = validate_credentials(user, form.password.data)
        if error:
            return render_template("login.html", form=form, error=error)

        login_user(user, remember=form.remember_me.data)
        next_page = find_next(backup="main.index")
        return redirect(next_page)

    return render_template("login.html", title="Sign In", form=form)


def find_next(backup):
    """
    find and validate the next argument when flask-login redirects
    from a protected page. Usually redirects back to the unathorized page.
    Use backup if next doesn't exist or fails to validate.

    e.g. try to access dashboard -> redirect to login -> redirected back to dashboard

    current validation only makes sure that next page is a relative path
    and doesn't have it's own netloc (netloc = www.example.com)
    """
    next_page = request.args.get("next")
    if not next_page or not url_parse(next_page).netloc != "":
        next_page = url_for(backup)
    return next_page


def validate_credentials(user, password):
    error = None
    if user is None:
        error = "Username not recognised"
    elif not user.check_password(password):
        error = "Incorrect password"
    return error


@server_bp.route("/logout/")
@login_required
def logout():
    logout_user()

    return redirect(url_for("main.index"))


@server_bp.route("/register/", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))

    form = RegistrationForm()
    if form.validate_on_submit():
        if existing_username(form.username.data):
            error = "already registered"
            return render_template("register.html", form=form, error=error)
        else:
            save_user(form.username.data, form.password.data)
            return redirect(url_for("main.login"))

    return render_template("register.html", title="Register", form=form)


def save_user(username, password):
    user = User(username=username)
    user.set_password(password)
    db.session.add(user)
    db.session.commit()


def existing_username(username):
    return bool(User.query.filter_by(username=username).first())

Thalia/templates/about.html
{% extends "base.html" %}

{% block content %}
<!-- Section1 -->
<div class="hero is-small is-bold">
  <section id="divider">
    <div class="hero-body">
      <div class="container">
        <div class="columns is-multiline is-vcentered">

          <!-- First row -->
          <div class="column is-half has-text-justified">
            <p class="title">
              <h2 class="title is-3">But how does it work?</h2>
            </p>
            <h1 class="subtitle is-4 has-text-weight-light has-text-black ">
              Imagine you’re nearing retirement and can’t afford to sit patiently through another financial crisis
              waiting for your investments to regain the value that they have lost.
              You're also passionate about finance, and devised an investment strategy, which couldn't possibly fail,
              you say. Imagine this dream portfolio consists of the following:
            </h1>
          </div>
          <div class="column has-text-centered">
            <!-- Dash here -->
            <img src="/static/images/about/pie.png" alt="">
            <!-- /Dash here -->
          </div>
          <!-- /First row -->

          <!-- Empty row row -->
          <div class="column is-12">&emsp;</div>
          <!-- /Empty row -->

          <!-- Second row -->
          <div class="column is-half has-text-centered">
            <!-- Dash here -->
            <img src="/static/images/about/chart.png" alt="">
            <!-- /Dash here -->
          </div>
          <div class="column has-text-justified">
            <h1 class="subtitle is-4 has-text-weight-light has-text-black ">
              That's great, but wouldn’t it be useful to consider similar portfolios, comparing how much they’ve lost in
              the worst year out of the last 50?
              Just to make sure that the dream portfolio indeed works.
              This process is known as backtesting and is usually done with the assistance of a computer.
            </h1>
          </div>
          <!-- /Second row -->

          <!-- Empty row row -->
          <div class="column is-12">&emsp;</div>
          <!-- /Empty row -->

          <!-- Third row -->
          <div class="column is-half has-text-justified">
            <h1 class="subtitle is-4 has-text-weight-light has-text-black ">
              That is where Thalia can help you, with Thalia, you can:
              <p>&emsp;</p>
              <ul style="list-style-type:disc;">
                <li>Specify an asset allocation using hundreds of assets across major asset classes</li>
                <li>Plot the performance of strategies against each other and an index benchmark</li>
                <li>Gain insight into a strategy’s key risk and performance metrics</li>
                <li>Model regular contributions and re-balancing strategies</li>
                <li>Save and share a portfolio to compare and discuss with peers</li>
              </ul>
            </h1>
          </div>

          <div class="column has-text-right">
            <img src="/static/images/Logos/small_logo.png" alt="">
          </div>
          <!-- /Third row -->

        </div>
      </div>
    </div>
  </section>
</div>
<!-- /Section1 -->
{% endblock %}

Thalia/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Thalia</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css" />
    <script src="https://cdn.jsdelivr.net/npm/clipboard@2/dist/clipboard.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <link rel="stylesheet" type="text/css" href="../static/stylesheets/base.css">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
</head>

<body>
    {% include 'navbar.html' %} {% block content %} {% endblock %}
    <footer class="footer">
        <div class="content has-text-centered">
            <div>
                <h1 class="subtitle is-5 has-text-weight-light has-text-black">
                    Don't forget to reach out to us on social media.
                </h1>
            </div>
            <div>
                <a href="https://twitter.com/Thalia99627941" class="twitter-link">
                    <i class="fab fa-twitter fa-2x has-color-inspire"></i>
                </a>
                <a href="https://www.facebook.com/Thalia-Backtester-101459001526511/" class="facebook-link">
                    <i class="fab fa-facebook fa-2x has-color-inspire"></i>
                </a>
            </div>
            <hr>
            <div>
                <h1 class="subtitle is-6 has-text-weight-light has-text-black">
                    The Site may provide certain financial market data that has been independently obtained by certain financial market information services. All data and Information is provided "as is" and the Information is intended solely as general information for educational
                    and entertainment purposes only and is neither professional stock broker advice for any investment nor a substitute for other professional advice and services from qualified financial services providers familiar with your financial
                    situation. Decisions based on Information contained within the Site are your sole responsibility. Always seek the advice of your financial advisor or other qualified financial services provider regarding any investment. The Information
                    is provided with the understanding that Thalia is not engaged in rendering professional services or advice, and is not a registered investment advisor. Your use of the Site is subject to this disclaimer: Thalia assumes no responsibility
                    for any consequences relating directly or indirectly to any action or inaction you take based on the Information or other material on this Site. You agree that Thalia, the Information Providers, and the Information Transmitters shall
                    not be liable in any way for the accuracy, completeness, timeliness, or correct sequencing of the Information, or for any decision made or action taken by you relying upon the Information. Thalia reserves the right to modify or discontinue,
                    temporarily or permanently, all or any portion of the Site with or without notice.
                </h1>
            </div>
        </div>
    </footer>
</body>

</html>

Thalia/templates/contact.html
{% extends "base.html" %}

{% block content %}
<style>
  .has-background-main {
      background: url(../static/images/index/thalia_background.jpg) center / cover;
    }
    .tag {
      color: #F26A4B !important;
      background-color: transparent !important;
    }
</style>
<!-- Section1 -->
<div class="hero is-medium is-bold has-background-main">
  <section id="divider">
    <div class="hero-body">
      <div class="container">
        <div class="columns is-multiline is-full">
          <div class="column is-12">
            &emsp;
          </div>
          <div class="column is-6">

          </div>
          <div class="column is-6">
            <h2 class="title is-2 has-text-light">
              Have something to say?
            </h2>
            <div class="column is-12">

            </div>
            <h1 class="subtitle is-4 has-text-weight-light has-text-justified has-text-light">
              Did you find something we should take a look at, or do you just have some general feedback? Remember, we are here to listen. Feel free to report your complaints and feedback here.
            </h1>
          </div>
          <div class="column is-half">

          </div>
          <div class="column">
            <form role="form" method="POST" novalidate>

                  {{ form.hidden_tag() }}

                  <div class="columns is-multiline">
                      <div class="column is-12">
                          &emsp;
                      </div>
                      <div class="column is-12">
                        {{ form.email(placeholder="Email Address",class="input is-medium", rows="1", class="textarea") }}
                      </div>
                      <div class="column is-12">
                          {{ form.title(placeholder="Title", class="input is-medium", rows="1", class="textarea")}}
                      </div>
                      <div class="column is-12">
                          {{ form.contents(placeholder="Contents",class="input is-large", rows="10", class="textarea") }}
                      </div>

                      
                      <div class="column is-12" style="text-align:right;">
                        <div class="form-footer has-text-right mt-10">
                            <button type="submit" class="button is-primary has-background-inspire4 raised is-clear send-feedback-btn" >Send Feedback</button>
                        </div>
                      </div>

                  </div>
              </form>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
  <!-- /Section1 -->
{% endblock %}

Thalia/templates/error.html
{% if error %}
<div class="notification is-warning">
  <p class="error"><strong>Error:</strong> {{ error }}
</div>
{% endif %}</p>

Thalia/templates/gallery.html
{% extends "base.html" %} {% block content %}

<div class="hero is-fullheight-with-navbar">
    <div class="section">
        {% if not portfolios %}
        <div class="container">
            <div class="columns is-vcentered">
                <div class="column has-text-centered">
                    <p class="subtitle">
                        It looks like you haven't saved any portfolios yet. Head to the
                        <a href="{{ url_for('/dashboard/') }}" class="has-color-inspire">dashboard</a> to start backtesting.
                    </p>
                </div>
            </div>
        </div>
        {% else %}
        <div id="gallery-ancestor" class="tile is-ancestor">
            {% for porto in portfolios %}
            <div class="tile is-parent is-4">
                <!-- <button> onclick="share_portfolio({{porto.id}}, this)">Share</> -->
                <article class="tile is-child box" style="background-color: #feedd0;">
                    <p class="title has-text-centered">{{porto.name}}</p>
                    <div class="level">
                        <button class="button level-item-left is-primary" onclick="window.location = '{{ url_for('/dashboard/') }}/{{porto.id}}'" style="background-color: #f26a4b;">
              Open
            </button>
                        <div class="button share-btn level-item-right is-info" data-portfolio="{{porto.id}}" style="background-color: #f23d3d;">
                            Make Public
                        </div>
                    </div>
                    {% if porto.link %}
                    <div class="columns">
                        {% else %}
                        <div id="public-link-div-{{porto.id}}" class="columns is-hidden">
                            {% endif %}
                            <!-- Target -->
                            <div class="column is-four-fifths">
                                <input id="public-link-{{porto.id}}" value="{{porto.link}}" class="input" readonly />
                            </div>
                            <div class="column has-text-right">
                                <!-- Trigger -->
                                <button class="button btn" data-clipboard-target="#public-link-{{porto.id}}">
                <i class="fa fa-clipboard" alt="Copy to clipboard"></i>
              </button>
                            </div>
                        </div>
                        <hr /> {% for asset in porto.strat.assets %}
                        <p class="subtitle" style="text-align: left;">
                            {% set ticker = asset.ticker.split("|")[0] %} {{ticker}}
                            <span style="float: right;">
              {{asset.weight}}%
            </span>
                        </p>
                        {% endfor %}
                </article>
                </div>
                {% endfor %}
            </div>
            {% endif %}
        </div>
    </div>

    <script type="text/javascript" src="{{url_for('static', filename='scripts/share-porto.js')}}"></script>
    {% endblock %}

Thalia/templates/index.html
{% extends "base.html" %} {% block content %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script rel="script" src="{{ url_for('static', filename='scripts/scroll-down.js') }}"></script>
<style>
    .has-background-main {
        background: url(../static/images/index/thalia_background.jpg) center / cover;
    }
    
    .has-background-stonks {
        background: url(../static/images/index/stonks.jpg) center / cover;
    }
</style>


<!-- Hero -->
<section class="hero has-background-main is-fullheight-with-navbar">
    <!-- Text -->
    <header class="hero-body">
        <div class="columns is-full">
            <div class="column is-half">
            </div>
            <div class="column is-hidden-mobile has-text-left single-spaced" style="top: 400px;">
                <h1 class="title is-1 has-text-white" style="padding-bottom: 0.3cm;">
                    What is Thalia?
                </h1>
                <h1 class="subtitle is-4 has-text-weight-light has-text-white has-text-justified">
                    Thalia is the reliable backtesting tool that helps you assess the viability of your investment strategies and compare them with various benchmarks.
                </h1>
            </div>
            <div class="column is-hidden-tablet has-text-centered single-spaced" style="top: 400px;">
                <h1 class="title is-1 has-text-white" style="padding-bottom: 0.3cm;">
                    Thalia
                </h1>
                <h1 class="subtitle is-4 has-text-right has-text-weight-light has-text-white has-text-justified">
                    - The Reliable Backtester
                </h1>
            </div>
        </div>
        </div>
    </header>
    <!-- /Text -->
    <!-- Arrow -->
    <main class="hero-foot center">
        <p class="level-item has-text-centered">
            <a class="ct-btn-scroll ct-js-btn-scroll btn-lg" href="#section2">
                <img alt="Arrow Down Icon" src="static/images/index/arrow.png">
            </a>
        </p>
    </main>
</section>
<!-- /Arrow -->
<!-- /Hero -->

<!-- Section2 -->
<div class="card is-light-bold">
    <section id="section2">
        <div class="card-content">
            <p class="title">
                <h2 class="title is-3">What is Backtesting?</h2>
            </p>
            <p class="subtitle">
                <h1 class="subtitle is-4 has-text-weight-light has-text-justified">
                    Before risking any real capital, traders generally like to know that their strategy will be profitable. While no-one can see into the future, we can sometimes get a good idea of performance by looking at the past. This process of analysing a portfolio
                    on historic data is known as backtesting.
                </h1>
            </p>
        </div>
        <footer class="card-footer">
            <p class="card-footer-item">
                <a class="tag" href="{{ url_for('main.about') }}" class="card-footer-item">Learn more</a>
            </p>
        </footer>
    </section>
</div>
<!-- /Section2 -->

<!-- Divider hero -->
<div class="hero is-medium has-background-stonks">
    <section id="divider">
        <div class="hero-body">
            <div class="container">
                &emsp;
            </div>
        </div>
    </section>
</div>
<!-- /Divider hero -->



<!-- Section3 -->
<div class="card">
    <section id="section3">

        <div class="card-content">
            <div class="columns is-vcentered">
                <div class="column is-half ">
                    {% if current_user.is_anonymous %}
                    <p class="title">
                        <h2 class="title is-3 has-text-centered">Still with us?</h2>
                    </p>
                    <h1 class="subtitle is-4 has-text-weight-light has-text-black has-text-justified">
                        Go ahead and create an account, or log in if you already have one. Once registered, you can backtest to your heart's content.
                    </h1>
                    {% else %}
                    <p class="title">
                        <h2 class="title is-3 has-text-centered">Already signed in?</h2>
                    </p>
                    <h1 class="subtitle is-4 has-text-weight-light has-text-black has-text-centered">
                        Why not jump right in and create your dream portfolio? If you would like to stick around, make sure to follow us on our social media pages to see our latest.
                    </h1>
                    {% endif %}
                </div>
                <!-- Register -->
                <div class="column">
                    <section id="contact" class="section section-light-grey is-medium">
                        <div class="container">
                            {% if current_user.is_anonymous %}
                            <div class="title-wrapper has-text-centered">
                                <h2 class="title is-2 is-spaced">Register</h2>
                                <div class="divider is-centered"></div>
                            </div>

                            <div class="content-wrapper">
                                <div class="columns">
                                    <div class="column">
                                        <div id="login_failed">
                                            {% if scroll %}
                                            <script>
                                                document.location.hash = '#' + '{{ scroll }}';
                                            </script>
                                            {% endif %} {% include 'error.html' %} {% include 'register_form.html' %}
                                        </div>
                                    </div>
                                </div>
                                {% else %}
                                <div class="media-content">
                                    <div class="content">
                                        <a class="twitter-timeline" href="https://twitter.com/Thalia99627941?ref_src=twsrc%5Etfw">Tweets by Thalia99627941</a>
                                        <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
                                    </div>
                                </div>
                                {% endif %}
                            </div>
                    </section>
                    </div>
                    <!-- /Register -->
                </div>
            </div>
    </section>
    </div>
    <!-- /Section3 -->
    {% endblock %}

Thalia/templates/login.html
{% extends "base.html" %}

{% block content %}
<style>
  .has-background-main {
    background: url(../static/images/index/thalia_background.jpg) center / cover;
  }
</style>

<!-- Login -->
<div class="hero is-medium has-background-main">
  <section id="contact" class="section section-light-grey is-large">
    <div class="container">
      <div class="content-wrapper">
        <div class="columns">
          <div class="column is-half"></div>
          <div class="column">
            <div class="title-wrapper has-text-centered">
              <h2 class="title is-2 is-spaced has-text-light">Log in</h2>
              <div class="divider is-centered"></div>
            </div>
            {% include 'error.html' %}

            {% include 'login_form.html' %}
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
<!-- /Login -->
{% endblock %}

Thalia/templates/login_form.html
<form role="form" method="post" novalidate>
  {{ form.hidden_tag() }}

  <div class="columns is-multiline">
    <div class="column is-12">
      {{ form.username(placeholder="Username", class="input is-medium", size=32)
      }}
    </div>

    <div class="column is-12">
      {{ form.password(placeholder="Password",class="input is-medium",
      type="password", size=32) }}
    </div>

    <div class="column is-12">
      <p class="has-text-light">
        {{ form.remember_me() }} {{ form.remember_me.label }}
      </p>
    </div>

    <div class="column is-7" style="text-align:left;">
      <div class="form-footer has-text-left mt-10">
        <button
          type="submit"
          class="button is-primary has-background-inspire4 raised is-clear signin-btn"
        >
          Sign in
        </button>
      </div>
    </div>

    <div class="column">
      <div class="form-footer has-text-right mt-10">
        <p class="has-text-light">New user?</p>
        <a class="tag" href="{{ url_for('main.register') }}">Sign up</a>
      </div>
    </div>
  </div>
</form>

Thalia/templates/navbar.html
<nav class="navbar" role="navigation" aria-label="main navigation" onclick="document.querySelector('.navbar-menu').classList.toggle('is-active');">
    <div class="navbar-brand">
        <a class="navbar-item navbar-logo" href="{{ url_for('main.index') }}">
            <img src="/static/images/Logos/large_logo.png" width="128" height="64">
        </a>
        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>
    <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
            <a href="{{ url_for('main.index') }}" class="navbar-item navbar-home">
        Home
      </a>
            <a href="{{ url_for('main.about') }}" class="navbar-item navbar-about">
        About
      </a> {% if not current_user.is_anonymous %}
            <a href="{{ url_for('main.gallery') }}" class="navbar-item navbar-gallery">
        My Portfolios
      </a> {% endif %} {% if not current_user.is_anonymous %}
            <a href="{{ url_for('/dashboard/') }}" class="navbar-item navbar-dashboard">
        Dashboard
      </a> {% endif %}
            <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link is-inspire">
          More
        </a>
                <div class="navbar-dropdown">
                    <a href="{{ url_for('main.us') }}" class="navbar-item navbar-about-us">
            About us
          </a>
                    <hr class="navbar-divider">
                    <a href="{{ url_for('main.contact') }}" class="navbar-item navbar-contact">
            Contact us
          </a>
                </div>
            </div>
        </div>
        <div class="navbar-end">
            <div class="navbar-item">
                <div class="buttons">
                    {% if current_user.is_anonymous %}
                    <a href="{{ url_for('main.register') }}" class="button is-primary has-background-inspire4 signup-btn">
                        <strong>Sign up</strong>
                    </a>
                    <a href="{{ url_for('main.login') }}" class="button is-light login-btn">
            Log in
          </a> {% else %}
                    <button class="button is-white greeting" disabled> Hi {{ current_user.username }}!</button>
                    <a href="{{ url_for('main.logout') }}" class="button is-white logout-btn">
            Log out
          </a> {% endif %}
                </div>
            </div>
        </div>
    </div>
    </div>
</nav>

Thalia/templates/register.html
{% extends "base.html" %} {% block content %}
<style>
    .has-background-main {
        background: url(../static/images/index/thalia_background.jpg) center / cover;
    }
</style>
<!-- Register -->
<div class="hero is-medium has-background-main">
    <section id="contact" class="section section-light-grey is-large">
        <div class="container">


            <div class="content-wrapper">
                <div class="columns">
                    <div class="column is-half">

                    </div>
                    <div class="column">
                        <div class="title-wrapper has-text-centered">
                            <h2 class="title is-2 is-spaced has-text-light">Register</h2>
                            <div class="divider is-centered"></div>
                        </div>
                        <div class="register-container">
                            {% include 'error.html' %} {% include 'register_form.html' %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
<!-- /Register -->
{% endblock %}